core/cart/urls.py
from django.urls import path,re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-service/",views.SessionAddServiceView.as_view(),name="session-add-service"),
    path("session/remove-service/",views.SessionRemoveServiceView.as_view(),name="session-remove-service"),
    path("session/update-service-quantity/",views.SessionUpdateServiceQuantityView.as_view(),name="session-update-service-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap,BlogSitemap,BlogTagSitemap,BlogCategorySitemap

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'blogcategory': BlogCategorySitemap,
    'blogtags': BlogTagSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('reserve/', include('reserve.urls')),
    path('stylist/', include('stylist.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
    path('reserveform/', include('reserveform.urls')),


    path('', include('website.urls')),

    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('api/users/', include('kavenegarapp.urls')),
] 

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from website.views import NewsletterView,aboutus,contactus, create_person,index,blog,blogposts,TermsAndCondition, postcategory,posttags,SendContactView


app_name = 'website'

urlpatterns = [
    path('', index , name='home'),
    path('about-us/', aboutus, name='about'),
    path('contact-us/', contactus, name='contact'),
    path('blog/', blog , name='blog-list'),
    path('terms-and-conditions/', TermsAndCondition, name='Terms-and-conditions'),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
    path("submit/ticket/",SendContactView.as_view(), name="submit-ticket"),
    path('beauty/', create_person, name='beauty'),
    path('beautyform/', create_person, name='beautyformaction'),

    path('category/<slug:slug>/',postcategory , name='blog-category'),
    path('tags/<slug:slug>/',posttags , name='blog-tags'),

    path('<slug:slug>/',blogposts , name='blog-detail'),

]

core/website/forms.py
from typing import Any
from django import forms
from .models import ContactModel,NewsLetter , Person


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = ["subject","full_name","email","phone_number","content"]
        
        error_messages = {
            'email': {
                'required': "فیلد ایمیل نمی تواند خالی باشد"
            },
            'content': {
                'required': "فیلد محتوا نمی تواند خالی باشد",
                'min_length': "طول محتوای وارد شده غیر مجاز است"
            },
            'subject': {
                'required': "فیلد  عنوان نمی تواند خالی باشد"
            },
            'full_name': {
                'required': "فیلد نام و نام خانوادگی نمی تواند خالی باشد"
            }
        }
    

class NewsLetterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, required=False)
    class Meta:
        model = NewsLetter
        fields = ['email',"first_name"]

    def clean_first_name(self):
        if len(self.cleaned_data['first_name']) > 0:
            raise forms.ValidationError("Please leave this field blank.")
        return self.cleaned_data['first_name']
    
    def save(self, commit=True):
        newsletter, created = NewsLetter.objects.get_or_create(email=self.cleaned_data.get("email"))
        return newsletter

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['number', 'email', 'first_name', 'last_name', 'question1', 'question2', 'question3', 'question4', 'question5', 'question6', 'question7', 'question8', 'question9', 'question10', 'question11', 'question12', 'question13', 'question14', 'question15', 'question16' , 'question17', 'question18' , 'question19', 'question20' , 'question21', 'question22', 'question23', 'question24', 'question25']
        # Add more fields as needed

core/dashboard/admin/views/contacts.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,

)


from website.models import NewsLetter,ContactModel
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import *
from django.db.models import F,Q
from django.core import exceptions


class ContactListView(LoginRequiredMixin,HasAdminAccessPermission, ListView):
    title = "لیست تماس ها"
    template_name = "dashboard/admin/contacts/contact-list.html"
    paginate_by = 10
    ordering = "-created_date"

    def get_paginate_by(self, queryset):
        """
        Paginate by specified value in querystring, or use default class property value.
        """
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_queryset(self):
        queryset = ContactModel.objects.all().order_by("-created_date")
        search_query = self.request.GET.get('q', None)
        ordering_query = self.request.GET.get('ordering', None)

        if search_query:
            queryset = queryset.filter(
                 Q(email__icontains=search_query) |
                 Q(subject__icontains=search_query) |
                 Q(content__icontains=search_query) |
                 Q(phone_number__icontains=search_query)
            )
        if ordering_query:
            try:
                queryset = queryset.order_by(ordering_query)
            except exceptions.FieldError:
                pass
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_result"] = self.get_queryset().count()
        return context



class ContactDetailView(LoginRequiredMixin,HasAdminAccessPermission, DetailView):
    title = "جزئیات تماس"
    template_name = "dashboard/admin/contacts/contact-detail.html"
    
    def get_object(self, queryset=None ):
        contact_obj = get_object_or_404(ContactModel,pk=self.kwargs.get("pk"))
        if not contact_obj.is_seen:
            contact_obj.is_seen = True
            contact_obj.save()
        return contact_obj
    

core/dashboard/admin/views/newsletters.py
from django.urls import reverse, reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    DeleteView,
)


from website.models import NewsLetter
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import *
from django.db.models import F, Q
from django.core import exceptions



class NewsletterListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    title = "لیست خبرنامه"
    template_name = "dashboard/admin/newsletters/newsletter-list.html"
    paginate_by = 10
    ordering = "-created_date"

    def get_paginate_by(self, queryset):
        """
        Paginate by specified value in querystring, or use default class property value.
        """
        return self.request.GET.get('paginate_by', self.paginate_by)
    
    def get_queryset(self):
        queryset = NewsLetter.objects.all().order_by("-created_date")
        search_query = self.request.GET.get('q', None)
        ordering_query = self.request.GET.get('ordering', None)

        if search_query:
            queryset = queryset.filter(
                Q(email__icontains=search_query)
            )
        if ordering_query:
            try:
                queryset = queryset.order_by(ordering_query)
            except exceptions.FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_result"] = self.get_queryset().count()
        return context


class NewsletterDeleteView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    title = "حذف خبرنامه"
    template_name = "dashboard/admin/newsletters/newsletter-delete.html"
    success_url = reverse_lazy("dashboard:admin:newsletter-list")
    success_message = "عضو مورد نظر با موفقیت حذف شد"

    def get_queryset(self):
        return NewsLetter.objects.all()

core/website/views.py
from django.http import HttpResponse
# slug is required
import string, random 
from django.utils.text import slugify 
# blog neede
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
#newsletterform
from .forms import ContactForm, NewsLetterForm, PersonForm
from django.contrib import messages
from django.views.generic import CreateView
# models.fields
from website.models import Person, SliderModel,CategorySEO, Post, Category , Tags ,PostSEO, TagsSEO

def index(request):
    posts = Post.objects.all().order_by('-id')
    categories = Category.objects.all()
    tags = Tags.objects.all()
    images = SliderModel.objects.all()

    context = {'posts': posts,
                'categories':categories,         
                'tags':tags,
                'images':images,
                }

    return render (request,'website/index.html', context)

def aboutus(request):
    return render (request,'website/about.html')

def contactus(request):
    return render (request,'website/contact.html')

def category(request):
    categories = Category.objects.filter(parent__isnull=True)  # top-level categories
    return render(request, 'website/blog.html', {'categories': categories})


def postcategory(request, slug):
    category = get_object_or_404(Category, slug=slug)  # Retrieve the category object based on the slug
    posts = Post.objects.filter(categories=category)  # Filter posts based on the category object

    seo = CategorySEO.objects.filter(Category_seo=category).first()

    paginator = Paginator(posts, 8)  # Show 10 posts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    

    context = {'category': category, 'page_obj': page_obj, 'seo': seo, 'posts' : posts}

    return render(request, 'website/category.html', context)

def posttags(request, slug):
    tag = get_object_or_404(Tags, slug=slug)  # Retrieve the category object based on the slug
    posts = Post.objects.filter(tags=tag)  # Filter posts based on the category object
    seo = TagsSEO.objects.filter(tags_seo=tag).first()

    paginator = Paginator(posts, 8)  # Show 10 posts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'tag': tag,'page_obj' :page_obj , 'posts': posts, 'seo' : seo}
    return render(request, 'website/tags.html', context)


def blog(request):
    posts = Post.objects.all().order_by('publish_date')
    categories = Category.objects.all()
    tags = Tags.objects.all()


    paginator = Paginator(posts, 4)  # Show 10 posts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    latests = Post.objects.all().order_by('publish_date')[:5]  # Example: fetching the 1 latest posts
    context = {'posts': posts,
                'latests': latests,
                'categories':categories,         
                'tags':tags,
                'page_obj' :page_obj}
    return render(request, 'website/blog.html', context)

def blogposts(request, slug): 
    post = get_object_or_404(Post, slug =slug )
    seo = PostSEO.objects.filter(post=post).first()  # Retrieve the first PostSEO object associated with the post
    posts = Post.objects.all()[:5]
    categories = Category.objects.all()
    tags = Tags.objects.all()

    context = {'slug': slug,
               'post' : post,
               'seo' : seo,
               'posts': posts,
               'categories':categories,
               'tags' : tags
               }

    return render(request, 'website/blog-detail.html', context) 

def TermsAndCondition(request):
    return render (request , 'website/termandcondition.html')

class SendContactView(CreateView):
    """
    a class based view to show index page
    """
    http_method_names = ['post']
    form_class = ContactForm

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, 'تیکت شما با موفقیت ثبت شد و در اسرع وقت با شما تماس حاصل خواهد شد')
        return super().form_valid(form)

    def form_invalid(self, form):
        # handle unsuccessful form submission
        messages.error(
            self.request, 'مشکلی در ارسال فرم شما پیش آمد لطفا ورودی ها رو بررسی کنین و مجدد ارسال نمایید')
        return redirect(self.request.META.get('HTTP_REFERER'))

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')
    
class NewsletterView(CreateView):
    http_method_names = ['post']
    form_class = NewsLetterForm
    success_url = '/'

    def form_valid(self, form):
        # handle successful form submission
        messages.success(
            self.request, 'از ثبت نام شما ممنونم، اخبار جدید رو براتون ارسال می کنم 😊👍')
        return super().form_valid(form)

    def form_invalid(self, form):
        # handle unsuccessful form submission
        messages.error(
            self.request, 'مشکلی در ارسال فرم شما وجود داشت که می دونم برا چی بود!! چون ربات هستید!')
        return redirect('website:index')
    
def create_person(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        args = {}
        if form.is_valid():
            form.save()
            users = Person.objects.all()

            return render(request, 'website/form/beautyform0.html', {'users': users})
    else:
        form = PersonForm() 
    
    args = {'form': form}
    return render(request, 'website/form/beauty.html', args)

core/templates/website/blog-detail.html
{% extends '../core/base.html' %}
{% load static %}

    {% block title %}{{ seo.title }}{% endblock title%}
    {% block seodescription %} {{ seo.description }}{% endblock seodescription%}
    {% block seoimage %} {{ seo.image }} {% endblock seoimage%}

{% block content %}

    <section class=""> 
    
        <!-- Page content-->
        <div class="bg-light ">
            <div class="container content-space-t-3 content-space-t-lg-5">
                <!-- Blog entries-->
                <header class="py-5 border-bottom mb-4">
                    <div class="">
                        <div class="header-blog-holder d-flex flex-column justify-content-between align-items-center">
                            <img class="mb-3" src="{{post.image.url}}" width="400px" height="auto" alt="{{post.title}}">
                            <h1 class="fw-bolder">
                                {{post.title}}
                            </h1>
                            <p class=" mb-0" > شرح مختصر :
                                {{post.post_summery | safe |truncatechars:100}}    
                            </p>
                            <div class="small text-muted">
                                <span> تاریخ انتشار : {{ post.publish_date }}</span>
                                <a href=""> <span> نویسنده : {{ post.author.get_full_name }}</span></a>
                                <a href=""> <span> دسته بندی : {{ post.categories }}</span></a> 
                                <span> تعداد بازدید : {{ post.total_views }}</span>

                            </div>
                        </div>
                    </div>
                </header>
                <div class="d-flex flex-row">
                    <div class="col-8">

                        <div class="blog-post-detail-holder mx-3 ">
                            <!-- Blog post-->
        
                            <div class="card mb-4 px-3">
                                <p class="card-text">  
                                    {{post.desc_1 | safe}}    
                                </p>
                            </div>
                        </div>
        
                    </div>
                    <!-- Side widgets-->
                    <div class="col-lg-4">
                        <!-- Search widget-->
                        <div class="card m-4">
                            <div class="card-header">
                                جستجو
                            </div>
                            <div class="card-body">
                                <div class="input-group">
                                    <input class="form-control" type="text" placeholder="جستجو بر اساس کلید واژه" aria-label="Enter search term..." aria-describedby="button-search" />
                                    <button class="btn btn-primary" id="button-search" type="button">جستجو</button>
                                </div>
                            </div>
                        </div>
                        <!-- Categories widget-->
                        <div class="card m-4">
                            <div class="card-header">دسته بندی ها</div>
                            <div class=" card-body">
                                <div class="">
                                {% for cat in categories %}
        
                                    <a class="cat-tag-item-card" href="{% url 'website:blog-category' slug=cat.slug %}"><span>{{cat.name}}</span></a>
                                {% endfor %}
                            </div>
        
                            </div>
                        </div>
                        <!-- tags widget-->
                        <div class="card m-4">
                            <div class="card-header">دسته بندی ها</div>
                            <div class="card-body">
                                <div class="cat-tag-item-card-holder">
                                {% for tag in tags %}
                                    <a class="cat-tag-item-card" href="{% url 'website:blog-tags' slug=tag.slug %}"><span>{{tag.name}}</span></a>
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Side widget posts-->
                        <div class="card m-4">
                            <div class="card-header">آخرین مقالات</div>
                            <div class="posts-list-latests card-body d-flex flex-column justify-content-between align-items-center">
                                {% for post in posts %}
                                <div class="posts d-flex">
                                    <a href="{% url 'website:blog-detail' slug=post.slug %}"><img src="{{post.image.url}} " width="100px" height="100px" alt="{{post.title}}"></a>
                                    <div class="content ms-3">
                                        </a><a href="{% url 'website:blog-detail' slug=post.slug %}"><div class="title">{{post.title}}</div></a>
                                        <div class="description">{{post.post_summery | safe |truncatechars:100}}</div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- Side widget products-->
        
                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock content%}

core/templates/website/blog.html
{% extends '../core/base.html' %}
{% load humanize %}
{% load static %}



{% block title %}Blog{% endblock title%}
{% block seodescription %} {{ seo.description }}{% endblock seodescription%}



{% block content %}


<section class=""> 
    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container content-space-t-3 content-space-t-lg-5">
            <div class="text-center">
                <h1 class="fw-bolder">
                    به وبلاگ ما خوش آمدید
                </h1>
                <p class="lead mb-0">
                    در این قسمت میتوانید با انتخاب دسته بندی مورد نظر خود سریع تر به مطلب مورد نظر برسید
                </p>
            </div>
        </div>
    </header>   
    <!-- Page content-->
    <div class="mt-4">
        <div class="row">
            <!-- Blog entries-->

            <div class=" col-lg-8">
                <!-- Nested row for non-featured blog posts-->
                <div class="blog-post-holder row m-5">
                    {% for post in page_obj %}    
                    <div class="col-lg-3 ">
                        <!-- Blog post-->

                        <div class="card mb-4">
                            <a href="{% url 'website:blog-detail' slug=post.slug %}"><img class="card-img-top" width="250px" height="auto" src="{{ post.image.url }}" alt="..." /></a>
                            <div class="card-body">
                                <div class="small text-muted">
                                    <span class="details"> تاریخ انتشار : {{ post.publish_date|naturaltime }}</span>
                                    <a href=""> <span class="author"> نویسنده : {{ post.author.get_full_name }}</span></a>
                                    <a href=""> <span class="category"> دسته بندی : {{ post.categories }}</span></a> 
                                    <span class="post-view"> تعداد بازدید : {{ post.total_views }}</span>

                                </div>
                                
                                <h2 class="card-title h4 title">موضوع مقاله : {{post.title}}</h2>
                                <p class="card-text summery"> شرح مختصر :
                                    {{post.post_summery |safe |truncatechars:100}}    
                                </p>
                                <a class="btn btn-primary read-more" href="{% url 'website:blog-detail' slug=post.slug %}">→ مطالعه بیشتر </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <!-- Pagination-->
                <nav aria-label="Pagination" >
                    <hr class="my-0" />
                    <ul class="pagination justify-content-center my-4">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">&laquo; first</a></li>
                        {% endif %}
                        <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Search widget-->
                <div class="card m-4">
                    <div class="card-header">
                        جستجو
                    </div>
                    <div class="card-body">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="جستجو بر اساس کلید واژه" aria-label="Enter search term..." aria-describedby="button-search" />
                            <button class="btn btn-primary" id="button-search" type="button">جستجو</button>
                        </div>
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card m-4">
                    <div class="card-header">دسته بندی ها</div>
                    <div class=" card-body">
                        <div class="">
                        {% for cat in categories %}

                            <a class="cat-tag-item-card" href="{% url 'website:blog-category' slug=cat.slug %}"><span>{{cat.name}}</span></a>
                        {% endfor %}
                    </div>

                    </div>
                </div>
                <!-- tags widget-->
                <div class="card m-4">
                    <div class="card-header">دسته بندی ها</div>
                    <div class="card-body">
                        <div class="cat-tag-item-card-holder">
                        {% for tag in tags %}
                            <a class="cat-tag-item-card" href="{% url 'website:blog-tags' slug=tag.slug %}"><span>{{tag.name}}</span></a>
                        {% endfor %}
                        </div>
                    </div>
                </div>
                <!-- Side widget posts-->
                <div class="card m-4">
                    <div class="card-header">آخرین مقالات</div>
                    <div class="posts-list-latests card-body d-flex flex-column justify-content-between align-items-center">
                        {% for post in latests %}
                        <div class="posts d-flex">
                            <a href="{% url 'website:blog-detail' slug=post.slug %}"><img src="{{post.image.url}} " width="100px" height="100px" alt="{{post.title}}"></a>
                            <div class="content ms-3">
                                </a><a href="{% url 'website:blog-detail' slug=post.slug %}"><div class="title">{{post.title}}</div></a>
                                <div class="description">{{post.post_summery | safe |truncatechars:100}}</div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>

</section>




{% endblock content%}

core/templates/website/category.html
{% extends '../core/base.html' %}
{% load static %}



{% block title %}{{ seo.title }}{% endblock title%}
{% block seodescription %} {{ seo.description }}{% endblock seodescription%}
{% block seoimage %} {{ seo.image }} {% endblock seoimage%}


{% block content %}

<div class="container content-space-t-3 content-space-t-lg-5">
    <!-- Nested row for non-featured blog posts-->
    <div class="blog-post-holder row m-5">
        {% for post in page_obj %}    
        <div class="col-lg-3 ">
            <!-- Blog post-->

            <div class="card mb-4">
                <a href="{% url 'website:blog-detail' slug=post.slug %}"><img class="card-img-top" width="250px" height="auto" src="{{ post.image.url }}" alt="..." /></a>
                <div class="card-body">
                    <div class="small text-muted">
                        <span class="details"> تاریخ انتشار : {{ post.publish_date }}</span>
                        <a href=""> <span class="author"> نویسنده : {{ post.author.get_full_name }}</span></a>
                        <a href=""> <span class="category"> دسته بندی : {{ post.categories }}</span></a> 
                        <span class="post-view"> تعداد بازدید : {{ post.total_views }}</span>

                    </div>
                    
                    <h2 class="card-title h4 title">موضوع مقاله : {{post.title}}</h2>
                    <a class="btn btn-primary" href="{% url 'website:blog-detail' slug=post.slug %}">→ مطالعه بیشتر </a>
                </div>
            </div>
        </div>
        {% endfor %}
        <nav aria-label="Pagination" >
            <hr class="my-0" />
            <ul class="pagination justify-content-center my-4">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">&laquo; first</a></li>
                {% endif %}
                <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
        
                {% endif %}
            </ul>
        </nav>
    </div>

    <!-- Pagination Controls -->
</div>

{% endblock content%}

core/templates/website/newsletter.html
{% extends '../core/base.html' %}
{% load static %}



{% block title %}About Us{% endblock title%}


{% block content %}




{% endblock content%}

core/templates/website/tags.html
{% extends '../core/base.html' %}
{% load static %}



{% block title %}{{ seo.title }}{% endblock title%}
{% block seodescription %} {{ seo.description }}{% endblock seodescription%}
{% block seoimage %} {{ seo.image }} {% endblock seoimage%}


{% block content %}

<h1 class="m-5">product detail</h1>



{% endblock content%}

core/templates/website/termandcondition.html
{% extends '../core/base.html' %}
{% load static %}

{% block title %}Terms & Conditions{% endblock title%}



{% block content %}





{% endblock content%}