core/accounts/urls.py
from django.urls import path,include
from . import views

app_name = "accounts"

urlpatterns = [
    # path('',include('django.contrib.auth.urls'))
    path('login/',views.LoginView.as_view(),name="login"),
    path('logout/',views.LogoutView.as_view(),name="logout"),
    path('register/',views.RegisterView,name="register"),
    path('verify-otp/', views.VerifyOTPView, name='verify_otp'),
]

core/cart/urls.py
from django.urls import path,re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-service/",views.SessionAddServiceView.as_view(),name="session-add-service"),
    path("session/remove-service/",views.SessionRemoveServiceView.as_view(),name="session-remove-service"),
    path("session/update-service-quantity/",views.SessionUpdateServiceQuantityView.as_view(),name="session-update-service-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap,BlogSitemap,BlogTagSitemap,BlogCategorySitemap

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'blogcategory': BlogCategorySitemap,
    'blogtags': BlogTagSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('reserve/', include('reserve.urls')),
    path('stylist/', include('stylist.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
    path('reserveform/', include('reserveform.urls')),


    path('', include('website.urls')),

    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('api/users/', include('kavenegarapp.urls')),
] 

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/dashboard/urls.py
from django.urls import path,include
from . import views

app_name = "dashboard"

urlpatterns = [
    path("home/",views.DashboardHomeView.as_view(),name="home"),
    
    # include admin urls
    path("admin/",include('dashboard.admin.urls')),
    
    # include customer urls
    path("customer/",include('dashboard.customer.urls')),
]

core/website/urls.py
from django.urls import path
from website.views import NewsletterView,aboutus,contactus, create_person,index,blog,blogposts,TermsAndCondition, postcategory,posttags,SendContactView


app_name = 'website'

urlpatterns = [
    path('', index , name='home'),
    path('about-us/', aboutus, name='about'),
    path('contact-us/', contactus, name='contact'),
    path('blog/', blog , name='blog-list'),
    path('terms-and-conditions/', TermsAndCondition, name='Terms-and-conditions'),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
    path("submit/ticket/",SendContactView.as_view(), name="submit-ticket"),
    path('beauty/', create_person, name='beauty'),
    path('beautyform/', create_person, name='beautyformaction'),

    path('category/<slug:slug>/',postcategory , name='blog-category'),
    path('tags/<slug:slug>/',posttags , name='blog-tags'),

    path('<slug:slug>/',blogposts , name='blog-detail'),

]

core/templates/partials/navs/center-nav.html
{% load static %}

<nav class="js-mega-menu navbar-nav-wrap">
    <!-- Default Logo -->
    <a class="navbar-brand" href="{% url 'website:home' %}" aria-label="Front">
        <img class="navbar-brand-logo" src="{% static 'svg/logos/logo.svg' %}" alt="Logo">
    </a>
    <!-- End Default Logo -->

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-default">
            <i class="bi-list"></i>
        </span>
        <span class="navbar-toggler-toggled">
            <i class="bi-x"></i>
        </span>
    </button>
    <!-- End Toggler -->

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link  {% if request.resolver_match.view_name  == 'website:home' %} active {% endif %}" href="{% url 'website:home' %}">صفحه اصلی</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name  == 'stylist:service-grid' %} active {% endif %}" href="{% url 'stylist:service-grid' %}">لیست خدمات</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name  == 'website:blog-list' %} active {% endif %}" href="{% url 'website:blog-list' %}">دانشنامه</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name  == 'website:beauty' %} active {% endif %}" href="{% url 'website:beauty' %}">فرم زیبایی</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name  == 'website:about' %} active {% endif %}" href="{% url 'website:about' %}">درباره ما</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name  == 'website:contact' %} active {% endif %}" href="{% url 'website:contact' %}">ارتباط با ما</a>
            </li>



            <li class="nav-item">
                <!-- Search -->
                <button class="btn btn-ghost-secondary btn-icon" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasNavbarSearch" aria-controls="offcanvasNavbarSearch">
                    <i class="bi-search"></i>
                </button>

                <!-- End Search -->

                <!-- Shopping Cart -->
                <!-- <button type="button" class="btn btn-ghost-secondary btn-icon" type="button"
                    data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarShoppingCart"
                    aria-controls="offcanvasNavbarShoppingCart">
                    <i class="bi-basket"></i>
                    <span class="cart-item-count ">3</span>
                </button> -->
                <a href="{% url 'cart:cart-summary' %}" class="btn btn-ghost-secondary btn-icon">
                    <i class="bi-basket"></i>
                    <span class="cart-item-count" id="total-cart-item-count">{{cart.get_total_quantity}}</span>
                </a>
                <!-- End Shopping Cart -->
                {% if request.user.is_authenticated %}

                <button class="btn btn-ghost-secondary btn-icon" id="dropdownMenuLink"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="avatar avatar-sm avatar-circle">
                        <img class="avatar-img" src="{{request.user.user_profile.image.url}}"
                            alt="Image Description">
                    </span>
                </button>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'dashboard:home' %}">پروفایل</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">خروج</a>
                </div>
                
                {% else %}
                <a class="btn btn-primary btn-transition" href="{% url 'accounts:login' %}">ورود</a>
                {% endif %}
                <a href="{% url 'website:contact' %}#FORM" class="btn btn-secondary mx-3">
                    <div class="contact-us-button" >فرم مشاوره رزرو</div>
                </a>
            </li>
        </ul>
    </div>
    <!-- End Collapse -->
</nav>

core/templates/partials/navs/top-nav.html
<nav class="top-nav navbar navbar-expand-lg">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"><a href="{% url 'website:home' %}">
                    <strong>پی خاک سنگ</strong>
                </a></li>
                <li class="nav-item"><a href="{% url 'website:about' %}">درباره ما</a></li>
                <li class="nav-item"><a href="{% url 'website:contact' %}">ارتباط با ما</a></li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">بانک اطاعات</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li class="dropdown-item"><a href="{% url 'website:blog-list' %}">مقالات</a></li>
                        <li class="dropdown-item"><a href="#">استاندارد</a></li>
                        <li class="dropdown-item"><a href="#">کتاب</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#">خدمات</a></li>
                <li class="nav-item"><a href="{% url 'website:Terms-and-conditions' %}">شرایط و قوانین</a></li>

            </ul>
        </div>
    </div>
</nav>