core/cart/urls.py
from django.urls import path,re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-service/",views.SessionAddServiceView.as_view(),name="session-add-service"),
    path("session/remove-service/",views.SessionRemoveServiceView.as_view(),name="session-remove-service"),
    path("session/update-service-quantity/",views.SessionUpdateServiceQuantityView.as_view(),name="session-update-service-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap,BlogSitemap,BlogTagSitemap,BlogCategorySitemap

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'blogcategory': BlogCategorySitemap,
    'blogtags': BlogTagSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('reserve/', include('reserve.urls')),
    path('stylist/', include('stylist.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
    path('reserveform/', include('reserveform.urls')),


    path('', include('website.urls')),

    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('api/users/', include('kavenegarapp.urls')),
] 

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/stylist/urls.py
from django.urls import path, re_path
from . import views

app_name = 'stylist'

urlpatterns = [
    # path('services/', ServicesListView , name='services-list'),
    # path('services/<slug:slug>', ServicesView , name='services'),
    # path('', StylistListView , name='stylist-list'),
    # path('<int:pk>', StylistView , name='stylist-account'),

    path("service/grid/",views.ShopServiceGridView.as_view(),name="service-grid"),
    re_path(r"service/(?P<slug>[-\w]+)/detail/",views.ShopServiceDetailView.as_view(),name="service-detail"),
    path("add-or-remove-wishlist/",views.AddOrRemoveWishlistView.as_view(),name="add-or-remove-wishlist")

]

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elole | {% block title %}{% endblock title%}</title>


    <!-- Additional SEO tags -->
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <meta name="robots" content="index, follow">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png'%}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest'%}"></head>
    {% include "./css-files.html" %}

    {% block extra_css_no_compress %} {% endblock extra_css_no_compress %}
    <meta name="description" content="{% block seodescription %}{% endblock seodescription%}">
    {% if seo.image %}
        <meta property="og:image" content="{% block seoimage %}{% endblock seoimage%}">
    {% endif %}
<body>
    {% include "../partials/header.html"%}

    <main id="content" role="main" class="mb-3">{% block content %}{% endblock content %}</main>


    {% include "../partials/footer.html"%}
        <!-- ========== SECONDARY CONTENTS ========== -->
    <!-- Sign Up -->

    <!-- Go To -->
    <a class="js-go-to go-to position-fixed" href="javascript:;" style="visibility: hidden;" data-hs-go-to-options='{
        "offsetTop": 700,
        "position": {
          "init": {
            "right": "2rem"
          },
          "show": {
            "bottom": "2rem"
          },
          "hide": {
            "bottom": "-2rem"
          }
        }
      }'>
         <i class="bi-chevron-up"></i>
     </a>
 
     <!-- Offcanvas Search -->
     <div class="offcanvas offcanvas-top offcanvas-navbar-search bg-light" tabindex="-1" id="offcanvasNavbarSearch">
         <div class="offcanvas-body">
             <div class="container">
                 <div class="w-lg-75 mx-lg-auto">
                     <div class="d-flex justify-content-end mb-3">
                         <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                             aria-label="Close"></button>
                     </div>
 
                     <div class="mb-7">
                         <!-- Form -->
                         <form action="{% url 'stylist:service-grid' %}">
                             <!-- Input Card -->
                             <div class="input-card">
                                 <div class="input-card-form">
                                     <input type="text" class="form-control form-control-lg" placeholder="جستجو محصولات"
                                         name="q" aria-label="جستجو محصولات">
                                 </div>
                                 <button type="submit" class="btn btn-primary btn-lg">جستجو کردن</button>
                             </div>
                             <!-- End Input Card -->
                         </form>
                         <!-- End Form -->
                     </div>
 
 
                 </div>
             </div>
         </div>
     </div>
 
     <!-- Offcanvas Search -->
     <div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasNavbarShoppingCart">
         <div class="offcanvas-header justify-content-between border-0 pb-0 ">
             <span> 3 کالا</span>
             <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
         </div>
 
         <div class="offcanvas-body">
 
             <div class="">
                 <!-- service -->
                 <div class="border-bottom  mb-4">
                     <div class="d-flex">
                         <div class="flex-shrink-0">
                             <div class="avatar avatar-lg ms-3">
                                 <img class="avatar-img" src="{% static 'img/320x320/img2.jpg' %}"
                                     alt="Image Description">
                             </div>
                         </div>
 
                         <div class="flex-grow-1">
                             <a class="h5" href="./service-overview.html">کوله پشتی ملی اصل</a>
 
                             <div class="d-grid py-3">
                                 <div class="text-body py-1">
                                     <div class="d-flex justify-content-start align-items-center">
                                         <span class="h6">تعداد:</span>
                                         <div class="quantity">
                                             <div class="input-group input-group-sm quantity-selector px-5">
                                                 <button type="button" class="btn btn-sm btn-icon btn-outline-primary">
                                                     <i class="bi-plus"></i>
                                                 </button>
                                                 <input type="number" class="form-control" value="2" min="1" max="10">
                                                 <button type="button" class="btn btn-sm btn-icon btn-outline-danger">
                                                     <i class="bi-dash"></i>
                                                 </button>
                                             </div>
                                         </div>
                                     </div>
 
                                 </div>
                                 <div class="text-body py-1">
                                     <div class="d-flex justify-content-start  align-items-center">
                                         <span class="h6">قیمت:</span>
                                         <span class="px-5">150000 تومان</span>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <!-- End service -->
                 <!-- service -->
                 <div class="border-bottom  mb-4">
                     <div class="d-flex">
                         <div class="flex-shrink-0">
                             <div class="avatar avatar-lg ms-3">
                                 <img class="avatar-img" src="{% static 'img/320x320/img3.jpg' %}"
                                     alt="Image Description">
                             </div>
                         </div>
 
                         <div class="flex-grow-1">
                             <a class="h5" href="./service-overview.html">تیشرت مشکی</a>
 
                             <div class="d-grid py-3">
                                 <div class="text-body py-1">
                                     <div class="d-flex justify-content-start align-items-center">
                                         <span class="h6">تعداد:</span>
                                         <div class="quantity">
                                             <div class="input-group input-group-sm quantity-selector px-5">
                                                 <button type="button" class="btn btn-sm btn-icon btn-outline-primary">
                                                     <i class="bi-plus"></i>
                                                 </button>
                                                 <input type="number" class="form-control" value="1" min="1" max="10">
                                                 <button type="button" class="btn btn-sm btn-icon btn-outline-danger">
                                                     <i class="bi-trash"></i>
                                                 </button>
                                             </div>
                                         </div>
                                     </div>
 
                                 </div>
                                 <div class="text-body py-1">
                                     <div class="d-flex justify-content-start  align-items-center">
                                         <span class="h6">قیمت:</span>
                                         <span class="px-5">100000 تومان</span>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <!-- End service -->
 
             </div>
 
             <div class="d-grid">
                 <p class="text-center">قیمت نهایی: 35000 تومان</p>
                 <a class="btn btn-primary btn-lg" href="/cart.html">سبد خرید</a>
             </div>
 
         </div>
     </div>
    {% include "./js-files.html" %}
    {% block extra_js %} {% endblock extra_js %}

    {% block extra_js_no_compress %} {% endblock extra_js_no_compress %}

    {% include 'messages.html' %}
</body>
</html>

core/templates/core/css-files.html
{% load static %}

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static 'css/vendor.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/font/bootstrap-icons.css' %}">


    <!-- CSS Front Template -->
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/toastify/toastify.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- CSS Font Awsome -->
    <link rel="stylesheet" href="{% static 'fontawsome/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawsome/regular.min.css' %}" >
    <link rel="stylesheet" href="{% static 'fontawsome/solid.min.css' %}" >
    <link rel="stylesheet" href="{% static 'fontawsome/brands.min.css' %}" >

    {% block extra_css %} {% endblock extra_css %}

    {% block extra_css_no_compress %} {% endblock extra_css_no_compress %}

core/templates/core/js-files.html
{% load static %}
   
    
<!-- fontawsome -->
<!-- <script src="{% static 'fontawsome/js/all.min.js' %}"></script> -->
<!-- <script src="{% static 'fontawsome/js/regular.min.js' %}"></script> -->

<!-- jquery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
{% comment %} <!-- bootstrap -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- jquery fancy box -->
<script src="{% static 'js/jquery-fancy-box.min.js' %}"></script> {% endcomment %}

<!-- owl carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>


    <!-- JS Implementing Plugins -->
    <script src="{% static 'js/vendor.min.js' %}"></script>

    <!-- JS Front -->
    <script src="{% static 'js/theme.min.js' %}"></script>

    <!-- JS Toastify -->
    <script src="{% static 'vendor/toastify/toastify.js' %}"></script>

    <!-- JS Plugins Init. -->
    <script>
        (function () {
            // INITIALIZATION OF HEADER
            // =======================================================
            new HSHeader('#header').init()

            new HSMegaMenu('.js-mega-menu', {
                desktop: {
                    position: 'left'
                }
            })


            // INITIALIZATION OF SHOW ANIMATIONS
            // =======================================================
            new HSShowAnimation('.js-animation-link')


            // INITIALIZATION OF BOOTSTRAP VALIDATION
            // =======================================================
            // HSBsValidation.init('.js-validate', {
            //     onSubmit: data => {
            //         data.event.preventDefault()
            //         alert('Submited')
            //     }
            // })


            // INITIALIZATION OF BOOTSTRAP DROPDOWN
            // =======================================================
            HSBsDropdown.init()


            // INITIALIZATION OF GO TO
            // =======================================================
            new HSGoTo('.js-go-to')


            // INITIALIZATION OF SWIPER
            // =======================================================
            var sliderThumbs = new Swiper('.js-swiper-shop-hero-thumbs', {
                watchSlidesVisibility: true,
                watchSlidesProgress: true,
                history: false,
                slidesPerView: 3,
                spaceBetween: 15,
                on: {
                    beforeInit: (swiper) => {
                        const css = `.swiper-slide-thumb-active .swiper-thumb-progress .swiper-thumb-progress-path {
                  opacity: 1;
                  -webkit-animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
                  animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
              }`
                        style = document.createElement('style')
                        document.head.appendChild(style)
                        style.type = 'text/css'
                        style.appendChild(document.createTextNode(css));

                        swiper.el.querySelectorAll('.js-swiper-thumb-progress')
                            .forEach(slide => {
                                slide.insertAdjacentHTML('beforeend', '<span class="swiper-thumb-progress"><svg version="1.1" viewBox="0 0 160 160"><path class="swiper-thumb-progress-path" d="M 79.98452083651917 4.000001576345426 A 76 76 0 1 1 79.89443752470656 4.0000733121155605 Z"></path></svg></span>')
                            })
                    },
                },
            });

            var swiper = new Swiper('.js-swiper-shop-classic-hero', {
                autoplay: true,
                loop: true,
                navigation: {
                    nextEl: '.js-swiper-shop-classic-hero-button-next',
                    prevEl: '.js-swiper-shop-classic-hero-button-prev',
                },
                thumbs: {
                    swiper: sliderThumbs
                }
            });


            // INITIALIZATION OF COUNTDOWN
            // =======================================================
            const oneYearFromNow = new Date()

            document.querySelectorAll('.js-countdown').forEach(item => {
                const days = item.querySelector('.js-cd-days'),
                    hours = item.querySelector('.js-cd-hours'),
                    minutes = item.querySelector('.js-cd-minutes'),
                    seconds = item.querySelector('.js-cd-seconds')

                countdown(oneYearFromNow.setFullYear(
                    oneYearFromNow.getFullYear() + 1),
                    ts => {
                        days.innerHTML = ts.days
                        hours.innerHTML = ts.hours
                        minutes.innerHTML = ts.minutes
                        seconds.innerHTML = ts.seconds
                    },
                    countdown.DAYS | countdown.HOURS | countdown.MINUTES | countdown.SECONDS
                )
            })
        })()

        var swiper = new Swiper('.js-swiper-shop-service', {
            effect: 'fade',
            autoplay: true,
            loop: true,
            navigation: {
                nextEl: '.js-swiper-shop-service-button-next',
                prevEl: '.js-swiper-shop-service-button-prev',
            },
            thumbs: {
                swiper: sliderThumbs
            }
        });

        var sliderThumbs = new Swiper('.js-swiper-shop-service-thumb', {
            slidesPerView: 3,
            watchSlidesVisibility: true,
            watchSlidesProgress: true,
            history: false,
        });
        // INITIALIZATION OF  QUANTITY COUNTER
        // =======================================================
        new HSQuantityCounter('.js-quantity-counter')
    </script>
    <!-- JS Custom-->
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- app js -->
    {% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
    <!-- JS Cart-->
    <script>
        function addToCart(service_id) {
     
            //console.log(service_id)
            $.ajax({
                url: "{%  url 'cart:session-add-service' %}",
                method: 'POST',
                data: {
                    service_id: service_id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
        
                },
                success: function (response) {
                    $("#total-cart-item-count").html(response.total_quantity)
                    console.log(response);
                    // do something with the response data
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                    // handle the error case
                }
            });
        }
        function addToWishlist(element,service_id) {
     
            //console.log(service_id)
            $.ajax({
                url: "{%  url 'stylist:add-or-remove-wishlist' %}",
                method: 'POST',
                data: {
                    service_id: service_id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
        
                },
                success: function (response) {

                    Toastify({
                        text:response.message,
                        className: `info`,
                        style: {
                          background: "blue",
                        }
                      }).showToast();
                    $(element).toggleClass('active');

                    // do something with the response data
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                    // handle the error case
                }
            });
        }
        
    </script>