core/cart/urls.py
from django.urls import path,re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-service/",views.SessionAddServiceView.as_view(),name="session-add-service"),
    path("session/remove-service/",views.SessionRemoveServiceView.as_view(),name="session-remove-service"),
    path("session/update-service-quantity/",views.SessionUpdateServiceQuantityView.as_view(),name="session-update-service-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap,BlogSitemap,BlogTagSitemap,BlogCategorySitemap

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'blogcategory': BlogCategorySitemap,
    'blogtags': BlogTagSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('reserve/', include('reserve.urls')),
    path('stylist/', include('stylist.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
    path('reserveform/', include('reserveform.urls')),


    path('', include('website.urls')),

    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('api/users/', include('kavenegarapp.urls')),
] 

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/stylist/urls.py
from django.urls import path, re_path
from . import views

app_name = 'stylist'

urlpatterns = [
    # path('services/', ServicesListView , name='services-list'),
    # path('services/<slug:slug>', ServicesView , name='services'),
    # path('', StylistListView , name='stylist-list'),
    # path('<int:pk>', StylistView , name='stylist-account'),

    path("service/grid/",views.ShopServiceGridView.as_view(),name="service-grid"),
    re_path(r"service/(?P<slug>[-\w]+)/detail/",views.ShopServiceDetailView.as_view(),name="service-detail"),
    path("add-or-remove-wishlist/",views.AddOrRemoveWishlistView.as_view(),name="add-or-remove-wishlist")

]

core/website/urls.py
from django.urls import path
from website.views import NewsletterView,aboutus,contactus, create_person,index,blog,blogposts,TermsAndCondition, postcategory,posttags,SendContactView


app_name = 'website'

urlpatterns = [
    path('', index , name='home'),
    path('about-us/', aboutus, name='about'),
    path('contact-us/', contactus, name='contact'),
    path('blog/', blog , name='blog-list'),
    path('terms-and-conditions/', TermsAndCondition, name='Terms-and-conditions'),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
    path("submit/ticket/",SendContactView.as_view(), name="submit-ticket"),
    path('beauty/', create_person, name='beauty'),
    path('beautyform/', create_person, name='beautyformaction'),

    path('category/<slug:slug>/',postcategory , name='blog-category'),
    path('tags/<slug:slug>/',posttags , name='blog-tags'),

    path('<slug:slug>/',blogposts , name='blog-detail'),

]

core/templates/partials/blog-carousel.html
{% load humanize %}
{% load static %}



<div class="pks-post-carousel container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div id="news-slider" class="owl-carousel">
			{% for post in posts %}
			<div class="post-slide">
				<div class="post-img">
					<img src="{{post.image.url}}" alt="">
					<a href="{% url 'website:blog-detail' post.slug %}" class="over-layer"><i class="fa fa-link"></i></a>
				</div>
				<div class="post-content">
					<h3 class="post-title">
					<a href="{% url 'website:blog-detail' post.slug %}">{{post.title}}</a>
					</h3>
					<p class="post-description">{{post.post_summery|safe|truncatechars:100 }}</p>
					<span class="post-date"><i class="fa fa-clock-o"></i>{{post.publish_date|naturaltime }}</span>
					<a href="website:blog-detail' post.slug" class="read-more">مطالعه مقاله</a>
				</div>
			</div>

            {% endfor %}

		</div>
	</div>
  </div>
</div>

core/templates/partials/footer.html
{% load static %}

    <!-- ========== FOOTER ========== -->
    <footer class="border-top bg-light">
        <div class="container">
            <div class="row justify-content-lg-between content-space-t-2 content-space-b-lg-2 ">
                <div class="col-lg-3 mb-5">
                    <div class="d-flex align-items-start flex-column h-100">
                        <!-- Logo -->
                        <a class="w-100 mb-3 mb-lg-auto" href="{% url 'website:home' %}" aria-label="Front">
                            <img class="brand" src="{% static 'svg/logos/logo.svg' %}" alt="Logo">
                        </a>
                        <!-- End Logo -->

                        <p class="text-muted small mb-0">
                            <p>ما اعتقاد داریم که
                                همیشه چیزی برای کشف و یادگیری وجود دارد، زیرا تنها با داشتن درک صحیح و دانستن اصول و تکنیک های اساسی است که می توانیم خلاقیت خود را فعال و تغذیه کنیم.
                            </p>
                        </p>

                    </div>
                </div>

                <div class="col-6 col-md-4 col-lg-3 ms-lg-auto mb-5 mb-lg-0">
                    <h5>ساعت کاری</h5>

                    <!-- table -->
                    <table><tbody>
                        <tr class=""><td>یکشنبه</td><td>18:00 – 11:00</td></tr>
                        <tr class=""><td>دوشنبه</td><td>18:00 – 11:00</td></tr>
                        <tr class=""><td>سه شنبه</td><td>18:00 – 11:00</td></tr>
                        <tr class=""><td>چهارشنبه</td><td>18:00 – 11:00</td></tr>
                        <tr class=""><td>پنجشنبه</td><td>18:00 – 11:00</td></tr>
                    </tbody></table>
                    <!-- End table -->
                </div>
                <!-- End Col -->

                <div class="col-6 col-md-4 col-lg-3 mb-5 mb-lg-0">
                    <h5>سایت مپ</h5>

                    <!-- List -->
                    <ul class="list-unstyled list-py-1">
                        <li><a class="link-sm text-secondary" href="{% url 'website:home' %}">صفحه اصلی</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'website:about' %}">درباره ما</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'website:contact' %}">ارتباط با ما</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'website:blog-list' %}">دانشنامه</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'website:beauty' %}">فرم زیبایی</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'stylist:service-grid' %}">خدمات</a></li>
                        <li><a class="link-sm text-secondary" href="{% url 'stylist:service-grid' %}">استایلیست ها</a></li>

                    </ul>
                    <!-- End List -->
                </div>
                <!-- End Col -->

                <div class="col-md-4 col-lg-2 mb-5 mb-lg-0">
                    <h5 class="mb-3">شبکه های اجتماعی</h5>

                    <!-- List -->
                    <ul>
                        <li class="icon-list-item my-3 list-unstyled">
                            <div class="icon-list-icon">
                                <a href="https://instagram.com/elhamrahmaniartistry/">
                                    <svg class="" width="50px" height="50px" viewBox="0 0 448 512" fill="#001634B3">
                                        <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
                                    </svg>
                                </a>
                            </div>
                            <div class="icon-list-text">اینستاگرام الهام رحمانی</div>
                        </li>
                        <li class="icon-list-item my-3 list-unstyled">
                            <span class="icon-list-icon">
                                <a href="https://instagram.com/leilarahmanistylistic/">
                                    <svg class="" width="50px" height="50px" viewBox="0 0 448 512" fill="#001634B3">
                                        <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
                                    </svg>
                                </a>
                            </span>
                            <span class="icon-list-text">اینستاگرام لیلا رحمانی</span>
                        </li>
                    </ul>
                    <!-- End List -->

                </div>
                <!-- End Col -->
            </div>
            <!-- End Row -->

            <hr class="my-0">

            <div class="row align-items-sm-center content-space-1">
                <div class="col-sm mb-4 mb-sm-0">
                    <!-- Socials -->
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                                <i class="bi-facebook"></i>
                            </a>
                        </li>

                        <li class="list-inline-item">
                            <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                                <i class="bi-google"></i>
                            </a>
                        </li>

                        <li class="list-inline-item">
                            <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                                <i class="bi-twitter"></i>
                            </a>
                        </li>

                        <li class="list-inline-item">
                            <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                                <i class="bi-github"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- End Socials -->
                </div>

                <div class="col-sm-auto">
                    <!-- List -->
                    <ul class="list-inline list-separator">
                        <li class="list-inline-item">
                            <a class="link-sm link-secondary" href="/page-privacy.html">حریم خصوصی و خط مشی</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="link-sm link-secondary" href="/page-terms.html">مقررات و شرایط</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="link-sm link-secondary" href="/#">مشاغل</a>
                        </li>
                    </ul>
                    <!-- End List -->
                </div>
            </div>
        </div>
    </footer>
    <!-- ========== END FOOTER ========== -->

core/templates/partials/header.html
{% load static %}

<header id="header" class="navbar navbar-expand-lg navbar-end navbar-absolute-top navbar-light navbar-show-hide"
    data-hs-header-options='{
    "fixMoment": 500,
    "fixEffect": "slide"
    }'>
    <div class="container">

        {% include "./navs/center-nav.html"%}
    </div>
</header>

core/templates/partials/price-list.html
{% load static %}

<div class="price-list-holder d-flex align-items-center justify-content-center mt-3">
    <div class="form-check form-switch d-flex flex-column align-items-center justify-content-center">
    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
    <label class="form-check-label mt-2" for="flexSwitchCheckChecked" id="flexSwitchCheckCheckedLable">
        برای تغییر لیست از بتن به خاک روی سوییچ کلیک کنید
    </label>
    </div>
</div>

<section class="price-list-beton">  
    <h2 style="text-align:center">{{pricelist.title}}</h2>        
    <p style="text-align:center">{{pricelist.upload_date}}</p>
    <div class="columns">
        <div class="price-list-columns">
            <ul class="pricebeton">
                <li class="header">
                    
                    پایه سه بتن
                    
                    </li>
                <li class="grey">
                    
            لیست تجهیزات بتن پایه سه        
                    </li>
                <li>
                    
            <a href="
            
            
            
            
            " target="_blank" class="list-hover">
            مشاهده لیست تجهیزات آزمایشگاه بتن  
                </a>           
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            دانلود شیوه نامه نظام مهندسی    </a>         
                    
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            لیست نیروی انسانی آزمایشگاه بتن    </a>         
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            فرمهای کاربردی    </a>         
                    </li>
                <li class="grey"><a href="{{pricelist.beton_3_document.url}}" class="buttonbeton">
                    
            
                پیش فاکتور پایه سه بتن
            
            
                    </a></li>
            </ul>
            </div>
            
            <div class="price-list-columns">
            <ul class="pricebeton">
                <li class="header">
                    
                    پایه دو بتن
                    
                    </li>
                <li class="grey">
                    
            لیست تجهیزات بتن پایه دو
            
                    </li>
                <li>
                    
            <a href="
            
            
            
            
            " target="_blank" class="list-hover">
            مشاهده لیست تجهیزات آزمایشگاه بتن  
                </a>           
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            دانلود شیوه نامه نظام مهندسی    </a>         
                    
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            لیست نیروی انسانی آزمایشگاه بتن    </a>         
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            فرمهای کاربردی    </a>         
                    </li>
                    <li class="grey"><a href="{{pricelist.beton_2_document.url}}" class="buttonbeton">

                    
                پیش فاکتور پایه دو بتن
            
                    </a></li>
            </ul>
            </div>
            
            <div class="price-list-columns">
            <ul class="pricebeton">
                <li class="header">
                    
                    پایه یک بتن
                    
                    </li>
                <li class="grey">
                    
            لیست تجهیزات بتن پایه یک
                    </li>
                <li>
                    
            <a href="
            
            
            
            
            " target="_blank" class="list-hover">
            مشاهده لیست تجهیزات آزمایشگاه بتن  
                </a>           
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            دانلود شیوه نامه نظام مهندسی    </a>         
                    
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            لیست نیروی انسانی آزمایشگاه بتن    </a>         
                    </li>
                <li>
                    
            <a href="#" class="list-hover">
            فرمهای کاربردی    </a>         
                    </li>
                    <li class="grey"><a href="{{pricelist.beton_1_document.url}}" class="buttonbeton">

                    
            پیش فاکتور پایه یک بتن
            
                    </a></li>
            </ul>
            </div>
    </div>
</section>  

<section class="price-list-khak">

    <h2 style="text-align:center">{{pricelist.title}}</h2>        
    <p style="text-align:center">{{pricelist.upload_date}}</p>
    <div class="columns">
        <div class="price-list-columns ">
        <ul class="price">
            <li class="header">
                
                پایه سه خاک
                
                </li>
            <li class="grey">
                
        لیست تجهیزات پایه سه خاک

        </li>
            <li>
                
        <a href="



        " target="_blank" class="list-hover">
        مشاهده لیست تجهیزات آزمایشگاه مکانیک خاک  
            </a>           
                </li>
            <li>
                
        <a href="#" class="list-hover">
        دانلود شیوه نامه نظام مهندسی    </a>         
                
                </li>
            <li>
                
        <a href="#" class="list-hover">

        لیست نیروی انسانی آزمایشگاه خاک   


        </a>
                </li>
            <li>
                
        <a href="#" class="list-hover">
        فرمهای کاربردی    </a>         
                </li>
                <li class="grey"><a href="{{pricelist.khak_3_document.url}}" class="buttonbeton">

                

            پیش فاکتور پایه سه خاک

                </a></li>
        </ul>
        </div>

        <div class="price-list-columns ">
        <ul class="price">
            <li class="header">
                
        پایه دو خاک        
                </li>
            <li class="grey">
                
        لیست تجهیزات پایه دو خاک
                </li>
            <li>
                
        <a href="





        " target="_blank" class="list-hover">
        مشاهده لیست تجهیزات آزمایشگاه مکانیک خاک  
            </a>           
                </li>
            <li>
                
        <a href="#" class="list-hover">
        دانلود شیوه نامه نظام مهندسی    </a>         
                
                </li>
            <li>
                
        <a href="#" class="list-hover">
            

        لیست نیروی انسانی آزمایشگاه خاک   

        </a>         
                </li>
            <li>
                
        <a href="#" class="list-hover">
        فرمهای کاربردی    </a>         
                </li>
                <li class="grey"><a href="{{pricelist.khak_2_document.url}}" class="buttonbeton">

                

            پیش فاکتور پایه دو خاک

                </a></li>
        </ul>
        </div>

        <div class="price-list-columns ">
        <ul class="price">
            <li class="header">
                
        پایه یک خاک

                </li>
            <li class="grey">
                
        لیست تجهیزات پایه یک خاک
                </li>
            <li>
                
        <a href="




        " target="_blank" class="list-hover">
        مشاهده لیست تجهیزات آزمایشگاه خاک
        </a>           
                </li>
            <li>
                
        <a href="#" class="list-hover">
        دانلود شیوه نامه نظام مهندسی    </a>         
                
                </li>
            <li>
                
        <a href="#" class="list-hover">

        لیست نیروی انسانی آزمایشگاه خاک   


        </a>         
                </li>
            <li>
                
        <a href="#" class="list-hover">
        فرمهای کاربردی    </a>         
                </li>
                <li class="grey"><a href="{{pricelist.khak_1_document.url}}" class="buttonbeton">

                
        پیش فاکتور پایه یک خاک

            </a></li>
        </ul>
        </div>
    </div>

</section>

core/templates/partials/product-carousel.html
{% load humanize %}
{% load static %}

<div class="pks-post-carousel container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div id="news-slider-2" class="owl-carousel">
            {% for product in products %}

            <div class="post-slide">
				<div class="post-img">
					<img src="{{product.image.url}}" alt="">
					<a href="{% url 'product:productdetails' product.slug %}" class="over-layer"><i class="fa fa-link"></i></a>
				</div>
				<div class="post-content">
					<h3 class="post-title">
					<a href="{% url 'product:productdetails' product.slug %}">{{product.title}}</a>
					</h3>
					<p class="post-description">{{product.summery |safe |truncatechars:100}}</p>
					<span class="post-date"><i class="fa fa-clock-o"></i>{{product.publish_date|naturaltime }}</span>
					<a href="#" class="read-more">مشاهده خدمت</a>
				</div>
			</div>

            {% endfor %}

		</div>
	</div>
  </div>
</div>

core/templates/partials/product-table.html
{% load static %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">نام خدمت</th>
        <th scope="col">قیمت</th>
        <th scope="col">قیمت در تخفیف ویژه</th>
        <th>صفحه خدمت</th>
        <th scope="col">تصویر خدمت</th>
      </tr>
    </thead>
    {% for product in products %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{product.title}}</td>
        <td>{{product.price}}</td>
        <td>{{product.offer_price}}</td>
        {% if product.slug %}
        <td><a href="{% url 'product:productdetails' slug=product.slug %}">صفحه خدمت</a></td>
        {% else %}
        <td><a href="">no slug</a></td>
        {% endif %}
        <td><img class="product-image-show" src="{{product.image.url}}" alt="{{product.title}}"></td>
      </tr>
    </tbody>
    {% endfor %}
</table>

core/templates/partials/slider.html
{% load static %}

<section class="pks_main_slider">
        <div id="pks_slider" class="pks_slider owl-carousel owl-carousel-single owl-theme">
        {% for image in images %}
          <div class="item">
            <img src="{{image.image.url}}" alt="{{image.alt}}">
        </div>
        {% endfor %}
        </div>
</section>